name: Scrape Projections

on:
  # Run on schedule (times are in UTC)
  schedule:
    # NBA/NHL: Every 2 hours from 10 AM to 11 PM ET (3 PM to 4 AM UTC)
    - cron: '0 15,17,19,21,23,1,3 * * *'
    # NFL Sunday: Every hour from 10 AM to 8 PM ET
    - cron: '0 15-24,0-1 * * 0'
  
  # Allow manual trigger from GitHub Actions tab
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
      
      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager pandas requests beautifulsoup4
      
      - name: Create config file
        run: |
          echo '{
            "rg_username": "${{ secrets.RG_USERNAME }}",
            "rg_password": "${{ secrets.RG_PASSWORD }}"
          }' > scraper_config.json
      
      - name: Run scraper (headless)
        run: python rotogrinders_scraper_github.py --headless
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/
          git diff --staged --quiet || git commit -m "Auto-update projections $(date +'%Y-%m-%d %H:%M')"
          git push
